= Lodger Agreement

Disclaimer: This is not to be used as a legal document. I'm not a lawyer. Use
this document at your own risk.

This is a template agreement for renting out a room to a lodger. Copy the
document below into an editor, fill in the fields at the top and then then
print out and then sign.


== Lodger Agreement

* Landlord's Name:
* Landlord's Address:
* Lodger's Name:
* Start Date:
* Deposit £:
* Rent £:
* Lodger's Room:
* Included Bills: eg. Water, Electricity, Gas, Council Tax, Internet, Cleaner

The Lodger agrees to pay to the Landlord the above Deposit and Rent on the Start
Date, and the Rent thereafter each calendar month. The Landlord agrees to
provide the Lodger's Room for the use of the Lodger. The Lodger also has the
shared use of the rest of the house (except the other bedrooms) and garden. The
Landlord agrees that there will be no extra charge for the the Included Bills.
The agreement may be terminated by either the Lodger or the Landlord, by giving
written notice at least one calendar month in advance.


Landlord's Signature:

Date:


Lodger's Signature:

Date:



This work is licensed under a
https://creativecommons.org/publicdomain/zero/1.0/[CC0 licence].
